# Generated by Django 5.0.6 on 2026-05-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("target_bottles", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Кампания",
                "verbose_name_plural": "Кампании",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("dushanbe", "Душанбе"),
                            ("sughd", "Согд"),
                            ("khatlon", "Хатлон"),
                            ("gbao", "ГБАО"),
                            ("rrs", "РРС"),
                            ("all", "Все"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("bottles_purchased", models.PositiveIntegerField(default=0)),
                ("bottles_recycled", models.PositiveIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("recycling_rate", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Дневные метрики",
                "verbose_name_plural": "Дневные метрики",
                "ordering": ["-date"],
                "unique_together": {("date", "region")},
            },
        ),
    ]
