# Generated by Django 5.0.6 on 2026-05-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bottles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[("purchase", "Purchase"), ("recycle", "Recycle")],
                        max_length=10,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("dushanbe", "Душанбе"),
                            ("sughd", "Согд"),
                            ("khatlon", "Хатлон"),
                            ("gbao", "ГБАО"),
                            ("rrs", "РРС"),
                        ],
                        default="dushanbe",
                        max_length=20,
                    ),
                ),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "bottle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="bottles.bottle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скан",
                "verbose_name_plural": "Сканы",
                "ordering": ["-created_at"],
            },
        ),
    ]
