# Generated by Django 5.0.6 on 2026-05-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
