# Generated by Django 5.0.6 on 2026-05-13 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bottles", "0001_initial"),
        ("scans", "0003_fix_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="bottle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to="bottles.bottle",
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="region",
            field=models.CharField(
                choices=[
                    ("dushanbe", "Душанбе"),
                    ("sughd", "Согд"),
                    ("khatlon", "Хатлон"),
                    ("gbao", "ГБАО"),
                    ("rrs", "РРС"),
                ],
                db_index=True,
                default="dushanbe",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="scan_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("recycle", "Recycle"),
                    ("referral_bonus", "Referral Bonus"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["scan_type", "created_at"], name="scans_scan_scan_ty_fa4edb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(
                fields=["user", "scan_type"], name="scans_scan_user_id_cd49d6_idx"
            ),
        ),
    ]
