# Generated by Django 5.0.6 on 2026-05-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_add_admin_adjustment_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
    ]
