# Generated by Django 5.0.6 on 2026-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_scan_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="streak_days",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
