# Generated by Django 5.0.6 on 2026-05-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecyclingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_tg", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("dushanbe", "Душанбе"),
                            ("sughd", "Согд"),
                            ("khatlon", "Хатлон"),
                            ("gbao", "ГБАО"),
                            ("rrs", "РРС"),
                        ],
                        default="dushanbe",
                        max_length=20,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Точка сбора",
                "verbose_name_plural": "Точки сбора",
            },
        ),
    ]
