# Generated by Django 5.0.6 on 2026-05-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_tg", models.CharField(blank=True, max_length=200)),
                ("points_cost", models.PositiveIntegerField()),
                ("image_url", models.URLField(blank=True)),
                ("stock_quantity", models.IntegerField(default=-1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Приз",
                "verbose_name_plural": "Призы",
                "ordering": ["points_cost"],
            },
        ),
        migrations.CreateModel(
            name="Redemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_spent", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("fulfilled", "Fulfilled")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prize",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="rewards.prize",
                    ),
                ),
            ],
            options={
                "verbose_name": "Погашение",
                "verbose_name_plural": "Погашения",
                "ordering": ["-redeemed_at"],
            },
        ),
    ]
