# Generated by Django 5.0.6 on 2026-05-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redemption",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("fulfilled", "Fulfilled"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
