# Generated by Django 5.0.6 on 2026-05-06 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("coca-cola", "Coca-Cola"),
                            ("coke-zero", "Coke Zero"),
                            ("fanta", "Fanta"),
                            ("sprite", "Sprite"),
                            ("schweppes", "Schweppes"),
                            ("fuse-tea", "Fuse Tea"),
                            ("piko", "Piko"),
                            ("bonaqua", "Bonaqua"),
                        ],
                        max_length=20,
                    ),
                ),
                ("volume_ml", models.PositiveIntegerField()),
                (
                    "package_type",
                    models.CharField(
                        choices=[("PET", "PET"), ("glass", "Glass"), ("can", "Can")],
                        default="PET",
                        max_length=10,
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "SKU",
                "verbose_name_plural": "SKUs",
            },
        ),
        migrations.CreateModel(
            name="Bottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("batch_number", models.CharField(blank=True, max_length=50)),
                ("produced_at", models.DateField(blank=True, null=True)),
                ("is_scanned", models.BooleanField(default=False)),
                ("is_recycled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bottles",
                        to="bottles.sku",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бутылка",
                "verbose_name_plural": "Бутылки",
            },
        ),
    ]
